/* XPM */
const char* aboutimage_xpm[] = {
"103 150 923 2",
"  	c #F0F0F0",
". 	c #EDEDED",
"+ 	c #EFEFEF",
"@ 	c #C5C8C8",
"# 	c #DBDDDD",
"$ 	c #889091",
"% 	c #818A8C",
"& 	c #E3E4E4",
"* 	c #727C7F",
"= 	c #233438",
"- 	c #AAAFB0",
"; 	c #EEEEEE",
"> 	c #A9AFB0",
", 	c #24353A",
"' 	c #778183",
") 	c #E0E1E1",
"! 	c #CFD2D2",
"~ 	c #182B2F",
"{ 	c #28393D",
"] 	c #BDC1C2",
"^ 	c #ECECEC",
"/ 	c #707A7C",
"( 	c #0A1E22",
"_ 	c #889092",
": 	c #C2C5C6",
"< 	c #203035",
"[ 	c #3E4C50",
"} 	c #E4E4E4",
"| 	c #E1E2E2",
"1 	c #5B6769",
"2 	c #0A1E23",
"3 	c #C2C6C7",
"4 	c #A3A9AA",
"5 	c #17292E",
"6 	c #616D70",
"7 	c #D6D7D8",
"8 	c #434F53",
"9 	c #293A3E",
"0 	c #CCCFD0",
"a 	c #82898B",
"b 	c #0F2227",
"c 	c #768083",
"d 	c #E8E9E8",
"e 	c #D5D6D7",
"f 	c #203236",
"g 	c #03171C",
"h 	c #1F3035",
"i 	c #687375",
"j 	c #A6ADAE",
"k 	c #CACDCE",
"l 	c #E2E3E3",
"m 	c #EDEDEE",
"n 	c #636E70",
"o 	c #02171C",
"p 	c #01161B",
"q 	c #0D2126",
"r 	c #304044",
"s 	c #5F6C6F",
"t 	c #8B9396",
"u 	c #B9BDBE",
"v 	c #E4E5E5",
"w 	c #B0B5B6",
"x 	c #102327",
"y 	c #03181D",
"z 	c #0D2125",
"A 	c #223438",
"B 	c #4B585C",
"C 	c #747F81",
"D 	c #9CA3A4",
"E 	c #C7CACB",
"F 	c #DCDDDD",
"G 	c #4E5B5D",
"H 	c #061A1F",
"I 	c #12262A",
"J 	c #28393E",
"K 	c #4B595C",
"L 	c #6F7879",
"M 	c #919799",
"N 	c #B0B4B6",
"O 	c #C3C7C7",
"P 	c #CED1D2",
"Q 	c #D8DADA",
"R 	c #DEDFDF",
"S 	c #E8E9E9",
"T 	c #EFF0F0",
"U 	c #8D9597",
"V 	c #0E2126",
"W 	c #03161B",
"X 	c #05191E",
"Y 	c #112327",
"Z 	c #243539",
"` 	c #36464A",
" .	c #49575A",
"..	c #556266",
"+.	c #717C7F",
"@.	c #BBBFC0",
"#.	c #2F3F43",
"$.	c #02161C",
"%.	c #324145",
"&.	c #C5C7C8",
"*.	c #E3E3E4",
"=.	c #CBCDCE",
"-.	c #D3D5D6",
";.	c #DADBDC",
">.	c #E7E8E8",
",.	c #EBEBEB",
"'.	c #707B7D",
").	c #051A1F",
"!.	c #04181D",
"~.	c #596668",
"{.	c #E4E4E5",
"].	c #CCCECE",
"^.	c #5C6769",
"/.	c #38464A",
"(.	c #626D72",
"_.	c #B3B7BA",
":.	c #BBBEBF",
"<.	c #13272B",
"[.	c #334247",
"}.	c #B1B6B6",
"|.	c #A4ABAC",
"1.	c #8E9798",
"2.	c #8E9698",
"3.	c #929A9C",
"4.	c #979FA0",
"5.	c #9FA6A8",
"6.	c #B4B9BA",
"7.	c #DDDEDF",
"8.	c #D3D6D6",
"9.	c #5A6568",
"0.	c #0E2025",
"a.	c #081B21",
"b.	c #AAB0B2",
"c.	c #D8DBDB",
"d.	c #415052",
"e.	c #0B1F23",
"f.	c #26373B",
"g.	c #192A2F",
"h.	c #0E2125",
"i.	c #122429",
"j.	c #16282C",
"k.	c #203136",
"l.	c #475559",
"m.	c #979EA0",
"n.	c #E5E6E6",
"o.	c #C9CCCD",
"p.	c #556165",
"q.	c #091D22",
"r.	c #293B3F",
"s.	c #7B8588",
"t.	c #CCCFD1",
"u.	c #E9E9EA",
"v.	c #9EA5A6",
"w.	c #091D21",
"x.	c #485559",
"y.	c #D6D8D8",
"z.	c #D5D7D7",
"A.	c #878E90",
"B.	c #03171D",
"C.	c #1E3134",
"D.	c #616E70",
"E.	c #AAB0B3",
"F.	c #D1D3D4",
"G.	c #324245",
"H.	c #02171B",
"I.	c #02161B",
"J.	c #14272C",
"K.	c #425155",
"L.	c #1F3034",
"M.	c #071A20",
"N.	c #667375",
"O.	c #DBDEDE",
"P.	c #DEE0E0",
"Q.	c #A6ACAD",
"R.	c #4E5B5E",
"S.	c #0C1F23",
"T.	c #0F2328",
"U.	c #586669",
"V.	c #BFC3C5",
"W.	c #E6E7E7",
"X.	c #6E797C",
"Y.	c #04191E",
"Z.	c #081A20",
"`.	c #9DA5A6",
" +	c #DFE1E2",
".+	c #8D9697",
"++	c #0C2024",
"@+	c #061A20",
"#+	c #13262B",
"$+	c #213338",
"%+	c #102329",
"&+	c #122529",
"*+	c #DDDFDF",
"=+	c #D6D8D9",
"-+	c #959C9F",
";+	c #4A585B",
">+	c #1D2F33",
",+	c #13262C",
"'+	c #6F7A7D",
")+	c #D2D4D5",
"!+	c #B1B5B7",
"~+	c #213237",
"{+	c #475659",
"]+	c #EEF0F0",
"^+	c #FFFFFF",
"/+	c #2B3B40",
"(+	c #1C2F33",
"_+	c #6A7578",
":+	c #889093",
"<+	c #23353A",
"[+	c #1B2D31",
"}+	c #566365",
"|+	c #778284",
"1+	c #667173",
"2+	c #2E3E41",
"3+	c #102227",
"4+	c #172A2F",
"5+	c #727E81",
"6+	c #556265",
"7+	c #848E90",
"8+	c #F8F8F8",
"9+	c #FEFEFE",
"0+	c #9EA5A7",
"a+	c #2C3D41",
"b+	c #01161C",
"c+	c #03161C",
"d+	c #314245",
"e+	c #3C4C50",
"f+	c #586568",
"g+	c #99A2A3",
"h+	c #B1B7B9",
"i+	c #27383B",
"j+	c #0B1E23",
"k+	c #A1A8A9",
"l+	c #D2D5D6",
"m+	c #9FA5A6",
"n+	c #0C1F24",
"o+	c #25373B",
"p+	c #C1C6C6",
"q+	c #F6F7F7",
"r+	c #DDE0E0",
"s+	c #EBEDED",
"t+	c #BABFC0",
"u+	c #314145",
"v+	c #687477",
"w+	c #AAB2B3",
"x+	c #A5ACAE",
"y+	c #808A8C",
"z+	c #576467",
"A+	c #172A2E",
"B+	c #061B20",
"C+	c #6D797C",
"D+	c #E6E8E8",
"E+	c #FEFDFD",
"F+	c #24363A",
"G+	c #2B3D41",
"H+	c #636F72",
"I+	c #A9AFB1",
"J+	c #344347",
"K+	c #1E2F33",
"L+	c #192B2F",
"M+	c #ADB4B5",
"N+	c #F7F8F8",
"O+	c #B3B9BA",
"P+	c #8A9294",
"Q+	c #FDFDFD",
"R+	c #FEFFFD",
"S+	c #FDFEFD",
"T+	c #E7EAEA",
"U+	c #879092",
"V+	c #1A2D31",
"W+	c #B4BABC",
"X+	c #969EA0",
"Y+	c #0E2226",
"Z+	c #344447",
"`+	c #DFE0E0",
" @	c #80898B",
".@	c #969FA0",
"+@	c #9DA3A5",
"@@	c #D1D4D5",
"#@	c #FCFCFC",
"$@	c #CED2D2",
"%@	c #091C21",
"&@	c #04171C",
"*@	c #485659",
"=@	c #DDDFE0",
"-@	c #FEFEFF",
";@	c #E9EBEB",
">@	c #858F91",
",@	c #102328",
"'@	c #4A585A",
")@	c #AAB0B1",
"!@	c #EAEAEA",
"~@	c #C5C8C9",
"{@	c #1C2D32",
"]@	c #DFE2E2",
"^@	c #E7E9E8",
"/@	c #525F62",
"(@	c #435255",
"_@	c #CACECF",
":@	c #D6D9DA",
"<@	c #4E5D5F",
"[@	c #0A1D21",
"}@	c #2D3D41",
"|@	c #606C70",
"1@	c #969EA1",
"2@	c #E9EAEA",
"3@	c #657173",
"4@	c #15282C",
"5@	c #5C686B",
"6@	c #324347",
"7@	c #1B2E32",
"8@	c #E3E6E5",
"9@	c #D4D7D8",
"0@	c #C6CACA",
"a@	c #ACB3B5",
"b@	c #F7F7F7",
"c@	c #E8EAEA",
"d@	c #929A9B",
"e@	c #1D2F34",
"f@	c #2E3F43",
"g@	c #25363B",
"h@	c #13272C",
"i@	c #091E23",
"j@	c #25373C",
"k@	c #747E82",
"l@	c #B9BEC0",
"m@	c #16282D",
"n@	c #1E3135",
"o@	c #848D8F",
"p@	c #4B5A5D",
"q@	c #04181E",
"r@	c #112428",
"s@	c #D9DDDC",
"t@	c #A0A7A9",
"u@	c #2D3E41",
"v@	c #8C9596",
"w@	c #EEEFF0",
"x@	c #EFF0F1",
"y@	c #D8DBDC",
"z@	c #D7DADB",
"A@	c #636F70",
"B@	c #0F2225",
"C@	c #7D8689",
"D@	c #697779",
"E@	c #CBCFCF",
"F@	c #E9E9E9",
"G@	c #D3D5D5",
"H@	c #3E4D50",
"I@	c #0A1F24",
"J@	c #1A2C32",
"K@	c #102428",
"L@	c #233437",
"M@	c #D7DBDB",
"N@	c #6D797B",
"O@	c #788284",
"P@	c #F1F2F2",
"Q@	c #FBFBFB",
"R@	c #99A1A2",
"S@	c #3A494B",
"T@	c #071B1F",
"U@	c #798386",
"V@	c #C5C9CA",
"W@	c #A7ADAF",
"X@	c #344549",
"Y@	c #0C2025",
"Z@	c #526063",
"`@	c #B5BABB",
" #	c #848D8E",
".#	c #596669",
"+#	c #15272C",
"@#	c #E0E2E3",
"##	c #C2C6C8",
"$#	c #49585B",
"%#	c #505D60",
"&#	c #8F9899",
"*#	c #F4F5F4",
"=#	c #667275",
"-#	c #27393D",
";#	c #1C2F34",
">#	c #112429",
",#	c #0B1F24",
"'#	c #233539",
")#	c #636E71",
"!#	c #9CA3A5",
"~#	c #CACDCD",
"{#	c #1C2E32",
"]#	c #E2E4E5",
"^#	c #EDEEEE",
"/#	c #A1A8AA",
"(#	c #8C9597",
"_#	c #A0A7A8",
":#	c #15282D",
"<#	c #949B9D",
"[#	c #E4E5E6",
"}#	c #717C7E",
"|#	c #ECEDED",
"1#	c #586466",
"2#	c #071B20",
"3#	c #7D888A",
"4#	c #FCFDFD",
"5#	c #D2D5D5",
"6#	c #636D70",
"7#	c #A5ADAD",
"8#	c #CCD0D1",
"9#	c #6B7779",
"0#	c #081C21",
"a#	c #3F4E51",
"b#	c #B8BDBE",
"c#	c #B6BABB",
"d#	c #102228",
"e#	c #37474B",
"f#	c #A3ABAC",
"g#	c #E1E4E4",
"h#	c #E2E4E4",
"i#	c #C0C4C5",
"j#	c #E1E3E4",
"k#	c #8B9496",
"l#	c #596568",
"m#	c #AEB3B4",
"n#	c #949D9E",
"o#	c #1A2D32",
"p#	c #D5D7D8",
"q#	c #455257",
"r#	c #27383C",
"s#	c #C7CCCD",
"t#	c #768081",
"u#	c #989FA0",
"v#	c #EFF1F0",
"w#	c #FEFEFD",
"x#	c #FAFAFA",
"y#	c #FAFAFB",
"z#	c #F2F3F3",
"A#	c #FCFCFD",
"B#	c #DCDFDF",
"C#	c #213336",
"D#	c #899294",
"E#	c #D9DBDC",
"F#	c #A3AAAB",
"G#	c #8C9495",
"H#	c #858E8F",
"I#	c #FBFCFC",
"J#	c #D6D8D7",
"K#	c #D1D4D4",
"L#	c #8F979A",
"M#	c #03191D",
"N#	c #616D71",
"O#	c #989FA2",
"P#	c #C1C5C6",
"Q#	c #EAEBEB",
"R#	c #C8CBCC",
"S#	c #344448",
"T#	c #091C22",
"U#	c #26383B",
"V#	c #3D4A4F",
"W#	c #FAFBFB",
"X#	c #DADDDD",
"Y#	c #768183",
"Z#	c #15272B",
"`#	c #707C7E",
" $	c #AEB4B5",
".$	c #99A0A1",
"+$	c #BEC2C2",
"@$	c #CBCECD",
"#$	c #E7E9E9",
"$$	c #AFB6B6",
"%$	c #BEC3C4",
"&$	c #3D4C4F",
"*$	c #636F73",
"=$	c #4E5C5F",
"-$	c #3A494D",
";$	c #081D22",
">$	c #3B4A4F",
",$	c #677275",
"'$	c #051A1E",
")$	c #5B686C",
"!$	c #C3C9CA",
"~$	c #C9CDCE",
"{$	c #DFE1E1",
"]$	c #F7F8F7",
"^$	c #B4BABB",
"/$	c #404F52",
"($	c #38474C",
"_$	c #E4E6E6",
":$	c #D2D6D6",
"<$	c #A9B0B1",
"[$	c #677375",
"}$	c #ACB2B4",
"|$	c #223437",
"1$	c #2F4044",
"2$	c #4F5D60",
"3$	c #7D878A",
"4$	c #657174",
"5$	c #415054",
"6$	c #1F3236",
"7$	c #324247",
"8$	c #C6C9C9",
"9$	c #E2E3E4",
"0$	c #1E3035",
"a$	c #182A2F",
"b$	c #A3ACAD",
"c$	c #FDFEFE",
"d$	c #2F3F42",
"e$	c #CCD0D0",
"f$	c #90999A",
"g$	c #E5E7E7",
"h$	c #B5BBBC",
"i$	c #1D2E32",
"j$	c #192B30",
"k$	c #192C31",
"l$	c #47565A",
"m$	c #3E4D51",
"n$	c #071C21",
"o$	c #0D2026",
"p$	c #7F898B",
"q$	c #C6CACB",
"r$	c #3B494D",
"s$	c #425053",
"t$	c #858D8F",
"u$	c #ACB2B3",
"v$	c #BBC0C1",
"w$	c #17292C",
"x$	c #F9F9F9",
"y$	c #C7CBCC",
"z$	c #747F82",
"A$	c #39484A",
"B$	c #2B3B3F",
"C$	c #435054",
"D$	c #B1B7B8",
"E$	c #9BA4A6",
"F$	c #12252A",
"G$	c #5D696C",
"H$	c #546265",
"I$	c #9BA2A4",
"J$	c #E5E5E6",
"K$	c #899193",
"L$	c #A3A8AA",
"M$	c #B2B8BA",
"N$	c #B1B6B8",
"O$	c #778184",
"P$	c #465459",
"Q$	c #BBC1C2",
"R$	c #EAECEC",
"S$	c #A7AEB0",
"T$	c #39484C",
"U$	c #6F7A7E",
"V$	c #D1D5D5",
"W$	c #1E3034",
"X$	c #38484C",
"Y$	c #727D7F",
"Z$	c #CBCECF",
"`$	c #2D3D42",
" %	c #717B7D",
".%	c #DCDEDE",
"+%	c #979E9F",
"@%	c #455357",
"#%	c #334347",
"$%	c #06191E",
"%%	c #213337",
"&%	c #445256",
"*%	c #7E878A",
"=%	c #E7E9EA",
"-%	c #404F53",
";%	c #7E8789",
">%	c #DCDDDE",
",%	c #E7E7E8",
"'%	c #6E797B",
")%	c #233338",
"!%	c #CDD0D0",
"~%	c #485759",
"{%	c #2C3C41",
"]%	c #3F4E52",
"^%	c #3B4B4E",
"/%	c #1A2C30",
"(%	c #B3B9BB",
"_%	c #5A6668",
":%	c #2A3B3E",
"<%	c #A9AEAF",
"[%	c #A1A7A9",
"}%	c #D7D9DA",
"|%	c #596569",
"1%	c #1E2F34",
"2%	c #344348",
"3%	c #868F91",
"4%	c #E0E1E2",
"5%	c #DBDDDE",
"6%	c #9EA4A6",
"7%	c #37464A",
"8%	c #536164",
"9%	c #B8BEBF",
"0%	c #838C8E",
"a%	c #182A2E",
"b%	c #606C6D",
"c%	c #BBBEBE",
"d%	c #CED1D1",
"e%	c #3D4B4F",
"f%	c #C6C9CA",
"g%	c #49575B",
"h%	c #EAEAEB",
"i%	c #EBECEC",
"j%	c #C0C3C5",
"k%	c #364548",
"l%	c #1F3136",
"m%	c #1A2C2F",
"n%	c #B4B8B9",
"o%	c #1C2D31",
"p%	c #99A0A2",
"q%	c #B4B9B9",
"r%	c #657073",
"s%	c #C1C4C5",
"t%	c #3E4E51",
"u%	c #5E6B6D",
"v%	c #E1E3E3",
"w%	c #CBCECE",
"x%	c #29383C",
"y%	c #626E70",
"z%	c #8F989A",
"A%	c #949C9D",
"B%	c #DADCDC",
"C%	c #E1E2E3",
"D%	c #E7E7E7",
"E%	c #606B6E",
"F%	c #1D2E33",
"G%	c #7F888B",
"H%	c #DDDEDE",
"I%	c #49565A",
"J%	c #3B4A4E",
"K%	c #D8D9DA",
"L%	c #8B9294",
"M%	c #1A2B2F",
"N%	c #ACB1B2",
"O%	c #C9CCCC",
"P%	c #39474B",
"Q%	c #E8E8E8",
"R%	c #6E7779",
"S%	c #28383C",
"T%	c #878E8F",
"U%	c #9AA0A3",
"V%	c #A4AAAB",
"W%	c #EEEFEF",
"X%	c #D2D4D4",
"Y%	c #697476",
"Z%	c #7C8587",
"`%	c #203135",
" &	c #878F91",
".&	c #3C4B4F",
"+&	c #A2A7A9",
"@&	c #A4AAAC",
"#&	c #334246",
"$&	c #606C6F",
"%&	c #768082",
"&&	c #2E3E42",
"*&	c #C8CCCD",
"=&	c #566266",
"-&	c #949B9C",
";&	c #B5BABC",
">&	c #CCCECF",
",&	c #38474B",
"'&	c #5B686A",
")&	c #667073",
"!&	c #A8AEAF",
"~&	c #364549",
"{&	c #445255",
"]&	c #D4D7D7",
"^&	c #A7ADAE",
"/&	c #AAAFB1",
"(&	c #1B2B31",
"_&	c #8B9395",
":&	c #415053",
"<&	c #3C4A4E",
"[&	c #889193",
"}&	c #C7CBCB",
"|&	c #5A6669",
"1&	c #4E5A5D",
"2&	c #314044",
"3&	c #3D4C50",
"4&	c #D9DADB",
"5&	c #EBEBEC",
"6&	c #868E91",
"7&	c #16292E",
"8&	c #B0B5B7",
"9&	c #626E71",
"0&	c #647073",
"a&	c #1E2F35",
"b&	c #697477",
"c&	c #192C30",
"d&	c #9DA4A5",
"e&	c #AFB4B5",
"f&	c #354448",
"g&	c #606D70",
"h&	c #BCC0C1",
"i&	c #6A7577",
"j&	c #16272C",
"k&	c #899194",
"l&	c #DADCDD",
"m&	c #29393E",
"n&	c #757E80",
"o&	c #3B494E",
"p&	c #707B7E",
"q&	c #4A5659",
"r&	c #374549",
"s&	c #05181D",
"t&	c #7F888A",
"u&	c #E5E5E5",
"v&	c #AFB5B6",
"w&	c #7F878A",
"x&	c #BDC1C1",
"y&	c #2C3C40",
"z&	c #ADB2B3",
"A&	c #505E61",
"B&	c #D0D2D3",
"C&	c #B5B9BA",
"D&	c #213236",
"E&	c #9AA1A3",
"F&	c #CCCFCF",
"G&	c #546164",
"H&	c #B1B6B7",
"I&	c #DFE0E1",
"J&	c #6B7578",
"K&	c #06191F",
"L&	c #0D2025",
"M&	c #ACB1B3",
"N&	c #969E9E",
"O&	c #1A2C31",
"P&	c #061B1F",
"Q&	c #39484B",
"R&	c #414F54",
"S&	c #091C20",
"T&	c #04181C",
"U&	c #778083",
"V&	c #B0B5B5",
"W&	c #223337",
"X&	c #B8BBBC",
"Y&	c #747D7F",
"Z&	c #0F2126",
"`&	c #102126",
" *	c #535E60",
".*	c #D9D9DA",
"+*	c #3B494C",
"@*	c #697376",
"#*	c #566264",
"$*	c #1C2E33",
"%*	c #A8ADB0",
"&*	c #CFD2D3",
"**	c #D4D6D7",
"=*	c #EFEFF0",
"-*	c #C4C8C9",
";*	c #4D5A5D",
">*	c #465357",
",*	c #ABB0B1",
"'*	c #515E61",
")*	c #415154",
"!*	c #B2B7B9",
"~*	c #D5D8D8",
"{*	c #EEEEEF",
"]*	c #0A1F23",
"^*	c #2D3C41",
"/*	c #01171B",
"(*	c #071C20",
"_*	c #1F3135",
":*	c #2A3B3F",
"<*	c #8A9394",
"[*	c #3F4F51",
"}*	c #646E71",
"|*	c #5B6568",
"1*	c #0F2226",
"2*	c #3C4C4F",
"3*	c #BDC2C2",
"4*	c #A5ABAC",
"5*	c #ACAFB0",
"6*	c #939798",
"7*	c #13262A",
"8*	c #546064",
"9*	c #14272B",
"0*	c #767F81",
"a*	c #E8E8E9",
"b*	c #AEB2B2",
"c*	c #27373C",
"d*	c #A0A6A7",
"e*	c #D4D5D6",
"f*	c #6C7679",
"g*	c #081C20",
"h*	c #28393C",
"i*	c #979D9E",
"j*	c #E1E1E2",
"k*	c #5B676A",
"l*	c #5F6A6D",
"m*	c #838B8C",
"n*	c #324246",
"o*	c #2B3C3F",
"p*	c #8A9293",
"q*	c #576366",
"r*	c #526062",
"s*	c #747E80",
"t*	c #5E696C",
"u*	c #515D60",
"v*	c #5C686A",
"w*	c #EFF0EF",
"x*	c #E0E2E2",
"y*	c #13252A",
"z*	c #5B6567",
"A*	c #D7D9D9",
"B*	c #D4D6D6",
"C*	c #071A1F",
"D*	c #3F4D50",
"E*	c #5F6B6D",
"F*	c #16292D",
"G*	c #455256",
"H*	c #A8ADAF",
"I*	c #9CA2A3",
"J*	c #14262B",
"K*	c #4F5D5F",
"L*	c #B7BBBB",
"M*	c #546264",
"N*	c #03181C",
"O*	c #B9BEBE",
"P*	c #E3E4E3",
"Q*	c #0B1E24",
"R*	c #5F6B6E",
"S*	c #4C595D",
"T*	c #2B3C40",
"U*	c #01171C",
"V*	c #6D787A",
"W*	c #535F62",
"X*	c #4B565A",
"Y*	c #838B8D",
"Z*	c #586366",
"`*	c #A3AAAC",
" =	c #D0D3D3",
".=	c #DEDFE0",
"+=	c #A0A8A9",
"@=	c #505E60",
"#=	c #2E3F42",
"$=	c #39494D",
"%=	c #7C8688",
"&=	c #999FA1",
"*=	c #425054",
"==	c #D9DBDB",
"-=	c #858D90",
";=	c #9BA1A3",
">=	c #081B20",
",=	c #A5ACAD",
"'=	c #EEEFEE",
")=	c #05181E",
"!=	c #B7BBBD",
"~=	c #90989A",
"{=	c #636E72",
"]=	c #E3E4E5",
"^=	c #5A6769",
"/=	c #364649",
"(=	c #303F44",
"_=	c #38484B",
":=	c #8C9395",
"<=	c #C4C7C8",
"[=	c #8A9395",
"}=	c #A7ACAD",
"|=	c #E3E5E5",
"1=	c #475558",
"2=	c #5D6A6D",
"3=	c #D6D9D9",
"4=	c #404E52",
"5=	c #CDCFD0",
"6=	c #495759",
"7=	c #DBDCDD",
"8=	c #0A1D22",
"9=	c #515D61",
"0=	c #98A0A1",
"a=	c #758082",
"b=	c #ADB2B4",
"c=	c #828C8E",
"d=	c #435154",
"e=	c #727B7E",
"f=	c #D2D3D4",
"g=	c #D3D4D5",
"h=	c #414F52",
"i=	c #081C22",
"j=	c #455155",
"k=	c #A0A6A8",
"l=	c #BFC3C4",
"m=	c #334447",
"n=	c #4A575C",
"o=	c #989EA1",
"p=	c #11252A",
"q=	c #747D80",
"r=	c #304145",
"s=	c #8C9396",
"t=	c #6F7A7C",
"u=	c #757F82",
"v=	c #BABEBF",
"w=	c #2E3E43",
"x=	c #6D777B",
"y=	c #CDD0D1",
"z=	c #798385",
"A=	c #2D3E43",
"B=	c #29393C",
"C=	c #707B7C",
"D=	c #CED0D1",
"E=	c #8F9799",
"F=	c #ECECED",
"G=	c #A9AEB0",
"H=	c #3A4A4D",
"I=	c #C8CBCB",
"J=	c #717A7D",
"K=	c #061A1E",
"L=	c #B2B7B8",
"M=	c #223338",
"N=	c #E6E6E7",
"O=	c #868E90",
"P=	c #B7BCBD",
"Q=	c #A2A8AA",
"R=	c #27373B",
"S=	c #828A8D",
"T=	c #566265",
"U=	c #838C8F",
"V=	c #646F72",
"W=	c #04191D",
"X=	c #112528",
"Y=	c #757F81",
"Z=	c #ABB0B2",
"`=	c #4D5B5E",
" -	c #465356",
".-	c #4D595D",
"+-	c #6D787B",
"                                              . +                                                                                                                                                             ",
"                                            + @ #                                                                                                                                                             ",
"                                            + $ % &                                                                                                                                                           ",
"                                            + * = - ;                                                                                                                                                         ",
"                                            + > , ' )                                                                                                                                                         ",
"                                              ! ~ { ]                                                                                                                                                         ",
"                                              ^ / ( _ .                                                                                                                                                       ",
"                                                : < [ }                                                                                                                                                       ",
"                                                | 1 2 3                                                                                                                                                       ",
"                                                + 4 5 6 ;                                                                                                                                                     ",
"                                                  7 8 9 0                                                                                                                                                     ",
"                                                  . a b c d                                                                                                                                                   ",
"                                                    e f g h i j k l m                                                                                                                                         ",
"                                                    ; n o p o q r s t u v +                                                                                                                                   ",
"                                                      w x p p p p y z A B C D E l ^ +                                                                                                                         ",
"                                                      F G o p p p p p p p p p H I J K L M N O P Q R S T                                                                                                       ",
"                                                      ^ U V p p p p p p p p p p p p p W X Y Z `  ...+.@.+                                                         + + +                                       ",
"                                                        O #.p p p p p p p p p p p p p p p p p p p $.H %.&.                                                      *.=.-.;.>.+                                   ",
"                                                        ,.'.).p p p p p p p p p p p p p p p p p p p p !.~.{.T + + + +                                       + ].^./.(._.S +                                   ",
"                                                          :.<.p p p p p p p p p p p p p p p p p p p p p [.}.|.1.2.3.4.5.6.7.+                               8.9.0.a.B b.c..                                   ",
"                                                          S d.p p p p p p p p p p p p p p p p p p p p p e.f.g.V h.b i.j.k.l.m.n.                        + o.p.q.p !.r.s.t.u.+                                 ",
"                                                            v.w.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p !.x.y.                  ; z.A.f.B.p p o C.D.E.& +                                 ",
"                                                            F.G.H.p p p p p p p p p p p I.J.K.L.I.p p p p p p p p y y o p p I.M.N.O.            + P.Q.R.S.p p p p p T.U.V..                                   ",
"                                                            W.X.Y.p p p p p p p p p p p Z.`. +.+++p p p p p p p @+#+$+%+o p p p &+c *+      . =+-+;+>+X p p p p p p ,+'+)+;                                   ",
"                                                            + !+~+p p p p p p p p p p p {+]+^+]+/+I.p p p p p p (+_+:+<+o p p p p g [+}+|+1+2+3+y I.p p p p p p p p 4+5+O >.;                                 ",
"                                                              R 6+y p p p p p p p p p 2 7+8+^+9+0+a+g p b+c+I.o T.d+e+T.p p p p p x f+g+h+i+H.p p p p p p p p p p p j+K.k+l+n.+                               ",
"                                                              + m+n+p p p p p p p p p o+p+q+r+s+8+t+u+S.v+w+x+y+z+A+B+o p p p p !.C+D+E+c.F+p p p p p p p p p p p p B+G+H+I+P.+                               ",
"                                                                v J+p p p p p p p p p o K+L+W K+M+N+O+P+Q+9+^+R+S+T+U+d+H p p p V+W+^+9+X+Y+p p p p p p p p p p p p I.w.Z+`.`+;                               ",
"                                                                   @!.p p p p p p p p p p p p p L..@+@@@^+^+^+^+^+^+#@$@v+%@p &@*@=@-@;@>@,@p p p p p p p p p p p p p n+'@)@Q !@+                             ",
"                                                                  ~@{@p p p p p p p p y ).Y.p p I.#+a+]@^+^+^+^+^+^+^+^+^@/@!.(@_@#@:@<@I o o y o p p p p p p p p p p [@}@|@1@0 2@+                           ",
"                                                                  v 3@!.p p p p p p p 4@5@6@Y.o p p 7@8@s+9@N+^+^+^+^+^+9+0@a@b@c@d@[+p y e@f@g@h@i@y p p p p p p p p X j@k@l@*.+                             ",
"                                                                  + k+m@p p p p p p o n@o@p@q@p p p r@s@t@u@v@w@^+^+^+^+^+x@y@z@A@B@p p Y+>@t+m.C@J Y.p p p p p p p p I D@E@F@+                               ",
"                                                                    G@H@I.p p p p p o I@J@K@p p p p L@M@N@I.,@O@P@^+9+Q@9+Q+R@S@T@I.p p q U@V@W@3.X@y p p p p p p p p Y@Z@`@Q W.;                             ",
"                                                                    +  #q.p p p p p p p p p p p p p .#;@v@+#j+.#@###$#%#&#*#=#g I.p p p I.2 -#;#>#,#y p p p p p p p p ).'#)#!#F..                             ",
"                                                                      ~#{#p p p p p p p p p p p p p ` ]#^#/#(#:@_@_#g :#<#[#H+Y.p p p p p I.y y g o o p p p p p p p p o J.}#: >.                              ",
"                                                                      |#1#I.p p p p p p p p p p p p 2#3#Q+4##@5#6#7# .~+U+8#9#0#p p p p p p p p p p p p p p p p p p p y a#b#l ^#                              ",
"                                                                        c#>#p p p p p p p p p p p I.d#e#f#g#Q@h#i#_#j#k#l#m#n#Y+p p p p p p p p p p p p p p p p p p p o o#o@p#;                               ",
"                                                                        ;.q#o p p p p p p p p p o r#(#s#t#u#v#w#9+x#9+y#z#A#B#C#p p p p p p p p p p p p p p p p p p p p #+D#E#S .                             ",
"                                                                        ,._ ,#p p p p p p p p p h O+q+#@F#G#H#:@I#^+^+Q@J#K#L#K@p p p p p p M#y p p p o p p p p p p p p z N#O#P#Q#                            ",
"                                                                          R#S#p p p p p T#F+U#V#0 W#X#Y#Z#`# $.$+$@$#$$$%$p+&$g p p p p p o $+*$=$-$6+{+o#2#o p p p p p p ;$>$M+S ;                           ",
"                                                                          S ,$'$$.p p Y.)$!$~${$]$^$/$).$.($_$r+:$3 <$[$%$8.}$|$H.p p p p I.2 1$$#2$_+3$4$5$6$Y@!.p p p p q@7$D#8$9$|#                        ",
"                                                                            Q.,@0$a$p 2 b$c$^+^+h#d$g p p V _#Q+N+#$e$t+g#f$g$h$i$I.I.p j$j$I.p y @+,#k$l$k#c m$n$p p p p o o$u+p$q$2@                        ",
"                                                                            n.r$s$t$f ,@u$9+9+q+v$W p p p p w$^$x$^+^+4#y$A z$c@h$A$B$C$D$E$$.p p p p p !.F$f G$H$I p p p p o L+I$J$                          ",
"                                                                              K$h L$1.H@M$j#N$O$P$I.p p p p g }@7+Q$R$S$T$I.n+U$g$O.V$|#Q+1@I.p p p p p p p y W$X$q p p p p >#Y$v                             ",
"                                                                              Z$`$ %.%+%@%#%[+$%p $.p p p p p o q.%%&%{#g p $.n+*%8+^+-@=%-%$.p p p p p p p p o Y.o p p I.j.;%>%                              ",
"                                                                              ,%'%)%!%; v$~%,@o p p o p p p p p $.V {%]%^%/%y o W$(%Q+c@_%X p p p p p p p p p p p p p H :%<%.                                 ",
"                                                                              + [%a$G#+   }%U+[.B+, |%1%p p p @+2%3%E 4%5%6%7%X y 8%9%0%+#p p p p p p p p p p p p $.a%b%c%+                                   ",
"                                                                                d%e%]%*.    2@f%.+- P.[%[+$.X g%i#h%      i%j%k%I.q.l%r@p p p p p p p p p p $.X m%1 n%`++                                     ",
"                                                                                . G#o%p%+             ; q%K r%{$              s%S#:#V T.(+a+e#^%t%-%-%5$;+u%% u v%+                                           ",
"                                                                                  w%x%y%l               + l S                 m ~#5.z%A% $~#B%P.| C%l h#D%. +                                                 ",
"                                                                                  ,.E%r i#                                        T + +                                                                       ",
"                                                                                    u F%G%!@                                                                                                                  ",
"                                                                                    H%I%J%K%                                                                                                                  ",
"                                                                                    i%L%M%N%                                                                                                                  ",
"                                                                                      O%P%l#2@                                                                                                                ",
"                                                                                      Q%R%S%8$                                                                                                                ",
"                                                                                        }.>+T%;                                                                                                               ",
"                                                                                        !@*@-%F.                                                                                                              ",
"                                                                                          U%[+V%W%                                                                                                            ",
"                                                                                          X%}@Y%,%                                                                                                            ",
"                                                                                          2@Z%`%Z$                                                                                                            ",
"                                                                                          + O+,  &                                                                                                            ",
"                                                                                            P./@.&J$                                                                                                          ",
"                                                                                              +&~+@&+                                                                                                         ",
"                                                                                              H%#&$&v                                                                                                         ",
"                                                                                              + %&&&s%                                                                                                        ",
"                                                                                                *&W$;%Q#                                                                                                      ",
"                                                                                                9$=&a#.%                                                                                                      ",
"                                                                                                . -&/%;&                                                                                                      ",
"                                                                                                  >&,&'&^                                                                                                     ",
"                                                                                                  2@)&f.Z$                                                                                                    ",
"                                                                                                    !&7@P++                                                                                                   ",
"                                                                                                    S ~&{&]&                                                                                                  ",
"                                                                                                      ;%/%^&W%                                                                                                ",
"                                                                                                      f%L+_+W.                                                                                                ",
"                                                                                                      S  %`%O%                                                                                                ",
"                                                                                                      + /&(&_&                                                                                                ",
"                                                                                                        p#:&<&*.                                                                                              ",
"                                                                                                        + [&~ +@+                                                                                             ",
"                                                                                                          }&W$|&|                                                                                             ",
"                                                                                                          ^ 1&}@j%                                                                                            ",
"                                                                                                            m#z o@Q#                                                                                          ",
"                                                                                                            ;.2&3&4&                                                                                          ",
"                                                                                                            5&6&7&8&                                                                                          ",
"                                                                                                              s%r 9&i%                                                                                        ",
"                                                                                                              l 0&9 k                                                                                         ",
"                                                                                                              + 5.a&2.|#                                                                                      ",
"                                                                                                              .  $1%&%!                                                                                       ",
"                                                                                                        n.H%^#f%b&#.c&d&.                                                                                     ",
"                                                                                                        k e&*+3@'%f&2#g&l                                                                                     ",
"                                                                                                        h&_&i&V e%' j&c&k&l&                                                                                  ",
"                                                                                                      2@ @m&x I.f.n&o&g T.p&>%                                                                                ",
"                                                                                                      5#= p p p g q&r&s&p :#t&u&                                                                              ",
"                                                                                                      v&I.p p p H w&x&y&p p V z&                                                                              ",
"                                                                                                      m.$.p p n+A&B&C&D&p p X E&                                                                              ",
"                                                                                                  + F&y%I.p 2#G&H&I&J&K&I.p L&M&                                                                              ",
"                                                                                                Q#N&O&p p P&%#V%Q&R&@+S&T&p 0#U&i%                                                                            ",
"                                                                                                V&W&I.p p d$X&Y&Z&I.`& *&+p $.#%y.                                                                            ",
"                                                                                              .*+*I.p p p }@@*:#$.X #*c#$*p p #+%*+                                                                           ",
"                                                                    . B%&***n.=*            -*;*H p p p p p o p p g >*+@a%p p T&g%**                                                                          ",
"                                                                  ,.,*'*e#)*X.!*}&~*{*    |#.+]*p p p p p p p p p p a.o%H p p I.Z 6.+                                                                         ",
"                                                                  @ ^*!.p /*(*_*:*<*,.    y.[*o p p p p p p p p p p p p p p p p z _&5&                                                                        ",
"                                                              ; . }*I.p p p p p 0#<#;   | |*c+p p p p p p p p p p p p p p p p p o '*`+                                                                        ",
"                                                            + F.&.f.p p p p p p Y+E&; W.3%1*p p p p p p p p p p p p p p p p p p p 2*o.3*!&4*x&&                                                               ",
"                                                            ^#5*6*7*p p p p p p Y.8*l  $, H.p p p p p p p p p p p p p p p p p p p 9*,&g@c&a$r#0*|                                                             ",
"                                                            a*b*C&>+p p p p p p p c*m#s$p p p p p p p p p p p p p p p p p p p p p p p p p p I.M. @+                                                           ",
"                                                            ) d*e*f*0#p p p p p p g*h*X p p p p p p p p p p p p p p p p p p p p p p p p p p p I.:*]&                                                          ",
"                                                            z.i*j*z.k*g*p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p n$l*@ .                                                       ",
"                                                          |#t$m*,.  >%&%p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p n*t@y.;                                                       ",
"                                                          ,.r%U + Q -&o*I.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o p*                                                            ",
"                                                          `+q*d&R r*>#o p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o s*+                                                           ",
"                                                        ) t*j+u*v*2#p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p ,#[&; W%w*                                                      ",
"                                                        x**@y*z*D&p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p n*i#`.k#5.A*;                                                   ",
"                                                        B*<&C*F$!.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.D*E*:#L&F*G*H*Q#                                                ",
"                                                      ; I*J*p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p L&$&V%z.;                                           ",
"                                                      Q%Y$q@p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o Y+K*L*.                                         ",
"                                                      l u%p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p H r#t&=+                                      ",
"                                                      `+M*p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p N*{&P                                     ",
"                                                      Q a#p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p 2#+.+                                   ",
"                                                      -*V+p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p _*O*W.                                ",
"                                                    P*1#$.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p $.Q*H+y.                              ",
"                                                .%o.% ,#p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p ,#R*#                             ",
"                                              ;.S*T*F$p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p U*p p p p p w.V*v                           ",
"                                          ^#~#%#y p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p X W*X*p p p p p p = c#                          ",
"                                          ] /$H p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p +#Y*Z*I.p p p p p A+`*        + {$ =.=.         ",
"                                      + h&S#!.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p 0#W$( p p p p p p m@+=        +$@=#=$=%=`+      ",
"                                    J$4.k.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p g a+&=>.W.D 4@p p o o *===    ",
"                                  9$s.l%o p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p $.#+-=6&1%p p p p p g i l   ",
"                                  ^&i.I.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p %+F$o p p p p p p ~+6.  ",
"                                  ;=>=p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o p p p p p p p p ~ ,=  ",
"                                '=Y$)=p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.p g y p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p A !=  ",
"                                | K.I.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.A ~=t*2#p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p $.{=]=  ",
"                                & ^=y p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o b /=Y*R c#(=p p p p p p p p p p p p p p p p p p p p p p p p p p p p $.o q., Q*_=v%    ",
"                                  :=H p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p T*<=i%: r&g p p p p p p p p p p p p p p p p p p p p p p p p p p I %%6+=&Y%h&Y$[=      ",
"                                B&/$g p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p 2 H+~@x.g p p p p p p p p p p p p p p p p p p p p p p p p p p p :*}=7.7.|   |=*+      ",
"                              @@1=g p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p o X o p p p p p p p p p p p p p p p p p p p p p p p p p p p p g 2=i%                ",
"                              O@2#p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.J.3=                ",
"                            ^ 4=p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p ;$~@                ",
"                          5=6=N*p p p p p p p p o !.p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p >#7=                ",
"                        ^  #8=p p p p p p p p p D&9=Z g p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.J*4@h.z %@$.p p p p p I.g@S                 ",
"                        v%s y p p p p p p p p n+0=Q a=P&p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p I.A&] u b#b=P$/*p p p p q.c=+                 ",
"                        `@, p p p p p p p p Y+$ . # d=I.p p p p p p p p p p p p p p p p p p p p p p !.o p p p p p p p p p p p p p p p p p p p p p p p p p p p p p H e=f=; g=h=p p p p i=r%)                   ",
"                      *.u%X p p p p p p p p f v$. 4 {@I.p p p p p p p p p p p p p p p p p p p p p I.Q&@%g p p p p p p p p p p p p p p p p p p p p p p p p p p p p p [@j=k=l=m=p p p Y.n=f%+                   ",
"                  + 2@o=p=p p p p p p p p p o+l=K#3&y p p p p p p p p p p p p p p p p p p p p p p I.q=~@Q&I.p p p p p p p p p p p p p p I.o p p p p p p p p p p p p p g 4+r=V p p $.J%0 ;                     ",
"            =*n.~#s=<&+#p p p p p p p p p j+t=l u=g p p p p p p p p p p p p p p p p p p p p p p y ^%V@+ v=w=g p p p p p p p p p p p p p m&2$e.o p p p p p p p p p p p p p p o p p y x=                        ",
"            y=z=f&V $.p p p p p p z A=[+B=C=5#D=%%o p p p p p p p p p p p p p p p p p p p p p p L&E=+   F=G=H=0.p p p p p p p p p p p p J%R#c /@}@H p p p p p p p p p p p p p p p j$W@                        ",
"        ; h&3&L&o p p p p p p p 7& @*&s%I=v F@J=K=p p p p p p p p p p p p p p p p p p p p p p p n+P+      . L=M=p p p p p p p p p p p 2#[$& N=5%}&d@1=V o p p p p p p p p p p p !.5@P.                        ",
"      {.O=A+$.p p p p p p $.H 5$P=.       Q#Q=l%p p p p p p p p p p p p p p p p p p p p p p p p 2#Y$+ + 7=h&R=$.p p p p p p p p p p q.H+#           {*l+0&!.p p p p p p p p p p 0#S=^                         ",
"      k=/%p p p p p p p I.z T=>&+       ]=.$`$y p p p p p p p p p p p p p p p p p p p p p p p p 2 U=n.H&6 L.2#p p p p p p p p p p q.k*A*              Q V=W=p p p p p p p p p p y b&n.                        ",
"    # f&o p p p p p p p X=Y=~*+     h%Z=`=5 o p p p p p p p p p p p p p p p p p p p p p p p p p g* -.-_*Q*p p p p p p p p p p p 0#$&]&              | V*,#p p p p p p p p p p p y +-W.                        "};
