#!/bin/bash

# 
# (c) 2009 Michael Wojciechowski
#

# Show a ncurses dialog which allows one to select a dir and later
# select a number of torrent files from it, so they can be copied to
# another destination, where a script used to 
# 

# Where to search for torrents.
IN=$HOME/rss
# Where to move torrents.
OUT=$HOME/btg/incoming
# What to execute after moving the torrents.
OUT_SCRIPT=`type -p in2btg` # "./btg_in.sh"
# dialog variables.
TEMP=/tmp/rss2btg.temp
H=40
W=79
MENUENTRIES=20

rm -f $TEMP
touch $TEMP

# find, use this value for -mtime.
MTIME="-7" # days
# One week, in hours.
((MAXOLD_HOURS=7*24))

SELECTED_DIR="$1"

F=""
DIRS=`find $IN -mindepth 1 -maxdepth 2 -type d`
TOTAL=0
for DIR in `echo $DIRS`
do
        # Find number of torrent files in dir.
	NUMBER_OF_TORRENTS=`find $DIR -mtime $MTIME -name \*.torrent|wc -l`
        if [ "$NUMBER_OF_TORRENTS" -gt 0 ] 
        then
          F="$F $DIR $NUMBER_OF_TORRENTS "
        fi
	((TOTAL=$TOTAL+$NUMBER_OF_TORRENTS))
done

if [ "$TOTAL" -eq 0 ]
then
  echo "No torrents found."
  exit 0
fi

if [ -z "$SELECTED_DIR" ]
then
dialog --menu 'Choose dir containing torrent files' $H $W $MENUENTRIES $F 2> $TEMP
STATUS=$?    
else
dialog --default-item "$SELECTED_DIR" --menu 'Choose dir containing torrent files' $H $W $MENUENTRIES $F 2> $TEMP
STATUS=$?
fi

case $STATUS in
  "0")
     ;; # pressed ok.
  *)
     echo "Script aborted by user ($STATUS)."
     rm -f $TEMP
     exit 0
esac

DIR=`cat $TEMP|sed -e "s/\"//g"`
rm -f $TEMP

# List files, sort by date, newest first.
FILES=`ls -1t $DIR/*.torrent`
MODS=(`stat --printf="%Y " $FILES`)
F=""
COUNT=0
NOW=`date +%s`

for FILE in `echo $FILES`
do
	MODTIME=${MODS[$COUNT]}
	((SINCE=($NOW-$MODTIME)/60/60))
	if [ "$SINCE" -lt $MAXOLD_HOURS ]
	then
	    BASE=${FILE##*/}
            F="$F $BASE ${SINCE}h off"
	fi
	((COUNT=COUNT+1))
done

# Select one or more torrents to add.
dialog --checklist 'Choose torrent file to add to current BTG session' $H $W $MENUENTRIES $F 2> $TEMP
STATUS=$?

case $STATUS in
  "0")
     ;; # pressed ok.
  *)
     echo "Script aborted by user ($STATUS)."
     rm -f $TEMP
     exit 0
esac

FILES=`cat $TEMP|sed -e "s/\"//g"`

# Move files.
for FILE in `echo $FILES`
do
    echo "Moving file $FILE"
    mv $DIR/$FILE $OUT 
    STATUS=$?
done

# Ask about adding more torrents.
dialog --yesno "Add another torrent?" $H $W 2> $TEMP
STATUS=$?
case $STATUS in
  "0")
     exec $0 "$DIR"
     ;; # pressed ok.
  *)
     echo "Adding torrents .."
     ;;
esac

# Number of torrents to add.
NUM_TO_ADD=`ls $OUT/*.torrent 2> /dev/null|wc -l`

COUNT=0
# run script which adds the torrents to BTG.
STATUS=0
(
    echo "00" ;

    for FILE in `seq $NUM_TO_ADD`
    do
	cd $OUT && $OUT_SCRIPT > /dev/null
	STATUS=$?

	((P=($COUNT*100)/$NUM_TO_ADD))

	echo "$P"
	((COUNT=$COUNT+1))
    done


    echo "100"
    ) | dialog --gauge "Adding $NUM_TO_ADD file(s) .. " 7 30

case $STATUS in
0) echo "File(s) added to BTG session." ;;
*) echo "File(s) NOT added to BTG session" ;;
esac

