.TH BTGQ 1 "01 June 2006"
.SH NAME
btgq \- download and add a torrent file to the first available session.
.SH SYNOPSIS
.B "btgq" 
.BI "URL"

.SH DESCRIPTION
.B "btgq" 
downloads a torrent using wget to a file and adds it to the first avaiable session. The btgcli application is used to communicate with the daemon, so it must be configured correctly before this script will work.

.SH OPTIONS
.TP
.BI "URL"
\- The URL of the torrent file to add.

.SH AUTHOR
Written by Michael Wojciechowski.

.SH "SEE ALSO"
btg(5), btgcli(1), wget(1).

.SH BUGS
No known bugs.
